os:
  - linux

language: go

go:
  - "1.10.x"

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - go get github.com/stretchr/testify/assert
  - go get github.com/karalabe/xgo
  - go get
  - go install

script:
  - go test -v